### PR TITLE
Indentation Problem on "else" statements.

### PR DESCRIPTION
**Pull request by nmandy-git**
I think there were some indentations issues, regarding enabled-state, los-tov-mode-enabled, long-distance and speed "if" loops.
The else statement had one tabulation more than needed. 
I try on my own with "speed" properties with success (setting 2 differents speed limits + not setting speed at all).
Hope that could help.

### CODE REVIEW

**Comment by daniel-chung-broadcom** [comment]
I don't think the changes are valid. The logic of the code is to 

1) first check to see if the key exists in the dictionary. If so
2) check to see if the value is valid
3) if no valid values are listed, else should trigger failure scenario

If we move else up on indentation as suggested, that means if any scenarios that do not contain the key would trigger failures, which I don't think is what we want. Please let me know your thoughts.

Thanks.

**Comment by nmandy-git** [comment]
Hi, 

Thanks for your return.

As far as I understand, values are only "checked" if they are given through the playbook, else they are gathered from the port itself.
I may be wrong.

I've tested the change on "speed" with and without passing the parameter and it works in my env.
When I use the script as-is, whatever is the value I pass on "speed" parameter, I always get "speed converted to unknown value" error returned.

Regards

**Comment by daniel-chung-broadcom** [comment]
Let me check out the specific scenario and get back to you. It feels like there is something going on and the code is not working as I meant. I'll keep you posted.

**Comment by nmandy-git** [comment]
Thanks a lot for your reactivity :)

**Comment by daniel-chung-broadcom** [comment]
I believe I found the issue. It looks like the code was written.

       if port_config["speed"] == "32Gig":
            port_config["speed"] = "32000000000"
        if port_config["speed"] == "16Gig":
            port_config["speed"] = "16000000000"
        if port_config["speed"] == "8Gig":
            port_config["speed"] = "10000000000"
        if port_config["speed"] == "10Gig":
            port_config["speed"] = "8000000000"
        if port_config["speed"] == "4Gig":
            port_config["speed"] = "4000000000"
        if port_config["speed"] == "2Gig":
            port_config["speed"] = "2000000000"
        if port_config["speed"] == "1Gig":
            port_config["speed"] = "1000000000"
        if port_config["speed"] == "Auto":
            port_config["speed"] = "0"
        else:
            result["failed"] = True
            result["msg"] = "speed converted to unknown value"
            return -1

what I really meant was

       if port_config["speed"] == "32Gig":
            port_config["speed"] = "32000000000"
        elif port_config["speed"] == "16Gig":
            port_config["speed"] = "16000000000"
        elif port_config["speed"] == "8Gig":
            port_config["speed"] = "10000000000"
        elif port_config["speed"] == "10Gig":
            port_config["speed"] = "8000000000"
        elif port_config["speed"] == "4Gig":
            port_config["speed"] = "4000000000"
        elif port_config["speed"] == "2Gig":
            port_config["speed"] = "2000000000"
        elif port_config["speed"] == "1Gig":
            port_config["speed"] = "1000000000"
        elif port_config["speed"] == "Auto":
            port_config["speed"] = "0"
        else:
            result["failed"] = True
            result["msg"] = "speed converted to unknown value"
            return -1

I have this fix along with 8gig/10gig issues that you fixed in my branch existing_zone_db.

if you want to pull the branch and check it out, that would be great. I tried setting the speed to 16gig, 8gig, 4gig & Auto. All of them worked fine for me. The only caveat is that if you set the speed to "Auto", the port speed that you get actually returns speed at which negotiation will take place. But you can tell that it did convert to auto-negotiate by looking at the switchshow output. I believe this is just the way FOS rest behaves. 

if you are good with these changes, I'll go ahead and close this pull and the other when the side branch existing_zone_db gets merged to main.

Thanks.

**Comment by nmandy-git** [comment]
Thanks for the update, I'm gonna give a try and reach you then (between today and tomorrow).
And I think your fix is the good one obviously, sorry for my bad contribution, I should have open an issue rather than this PR.

I'll be back soon,

Thanks,
Nico

**Comment by daniel-chung-broadcom** [comment]
Thanks. It is absolutely not a bad contribution. I would not have found out about both issues without you bringing them up.  You are welcome to use either pull or issue to bring up things to attention. Perfectly fine either way.

**Comment by nmandy-git** [comment]
Hi,
I've tested out with differents speeds (Auto, 8 16 32) and without specifying speed, seems working great now!
Good job!
Thanks,

**Comment by daniel-chung-broadcom** [comment]
great. I'll close these two pulls once the changes are merged to the main and uploaded to galaxy.ansible.com. Thanks.

**Comment by daniel-chung-broadcom** [comment]
the changes have been merged to main and uplodated to galaxy.ansible.com. Closing the pull as agreed previously.

**Pull request closed without merging**
